"""Add Language model and user.language_id foreign key

Revision ID: 112a2c60c42f
Revises: 7fce825f5bd0
Create Date: 2025-07-23 20:01:10.921449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112a2c60c42f'
down_revision = '7fce825f5bd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'languages',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('name', sa.String(length=100), nullable=False, unique=True),
    )
    op.add_column('users', sa.Column('language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'languages', ['language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'language_id')
    op.drop_table('languages')
    # ### end Alembic commands ### 