"""Add Corporate Profile and Full Time Job models

Revision ID: 2ea247c60da0
Revises: 6db953b3569d
Create Date: 2025-08-27 05:40:47.119821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea247c60da0'
down_revision = '6db953b3569d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('company_size', sa.Enum('STARTUP', 'SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE', name='companysize'), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_corporate_profiles_company_name'), 'corporate_profiles', ['company_name'], unique=False)
    op.create_index(op.f('ix_corporate_profiles_id'), 'corporate_profiles', ['id'], unique=False)
    op.create_table('full_time_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('work_mode', sa.String(length=20), nullable=False),
    sa.Column('experience_level', sa.String(length=20), nullable=False),
    sa.Column('skills_required', sa.Text(), nullable=False),
    sa.Column('min_salary', sa.Float(), nullable=False),
    sa.Column('max_salary', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['corporate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_full_time_jobs_id'), 'full_time_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_full_time_jobs_title'), 'full_time_jobs', ['title'], unique=False)
    op.drop_index(op.f('idx_certification_centers_is_deleted'), table_name='certification_centers')
    op.drop_index(op.f('idx_certification_centers_name'), table_name='certification_centers')
    op.drop_index(op.f('idx_companies_country'), table_name='companies')
    op.drop_index(op.f('idx_companies_is_deleted'), table_name='companies')
    op.drop_index(op.f('idx_companies_name'), table_name='companies')
    op.drop_index(op.f('idx_education_facilities_country'), table_name='education_facilities')
    op.drop_index(op.f('idx_education_facilities_is_deleted'), table_name='education_facilities')
    op.drop_index(op.f('idx_education_facilities_name'), table_name='education_facilities')
    op.drop_index(op.f('idx_locations_code'), table_name='locations')
    op.drop_index(op.f('idx_locations_is_deleted'), table_name='locations')
    op.drop_index(op.f('idx_locations_name'), table_name='locations')
    op.drop_index(op.f('idx_otps_created_at'), table_name='otps')
    op.drop_index(op.f('idx_otps_email'), table_name='otps')
    op.drop_index(op.f('idx_otps_email_expires'), table_name='otps')
    op.drop_index(op.f('idx_otps_email_used_expires'), table_name='otps')
    op.drop_index(op.f('idx_otps_is_used'), table_name='otps')
    op.drop_index(op.f('idx_project_images_project_id'), table_name='project_images')
    op.drop_index(op.f('idx_projects_is_deleted'), table_name='projects')
    op.drop_index(op.f('idx_projects_user_id'), table_name='projects')
    op.add_column('proposals', sa.Column('full_time_job_id', sa.Integer(), nullable=True))
    op.alter_column('proposals', 'gig_job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'proposals', 'full_time_jobs', ['full_time_job_id'], ['id'])
    op.drop_index(op.f('idx_skills_is_deleted'), table_name='skills')
    op.drop_index(op.f('idx_skills_name'), table_name='skills')
    op.drop_index(op.f('idx_user_skills_skill_id'), table_name='user_skills')
    op.drop_index(op.f('idx_user_skills_user_id'), table_name='user_skills')
    op.drop_index(op.f('idx_users_apple_id'), table_name='users')
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_email_active'), table_name='users')
    op.drop_index(op.f('idx_users_facebook_id'), table_name='users')
    op.drop_index(op.f('idx_users_google_id'), table_name='users')
    op.drop_index(op.f('idx_users_is_active'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('idx_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_index(op.f('idx_users_facebook_id'), 'users', ['facebook_id'], unique=False)
    op.create_index(op.f('idx_users_email_active'), 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('idx_users_apple_id'), 'users', ['apple_id'], unique=False)
    op.create_index(op.f('idx_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_skills_skill_id'), 'user_skills', ['skill_id'], unique=False)
    op.create_index(op.f('idx_skills_name'), 'skills', ['name'], unique=False)
    op.create_index(op.f('idx_skills_is_deleted'), 'skills', ['is_deleted'], unique=False)
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.alter_column('proposals', 'gig_job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('proposals', 'full_time_job_id')
    op.create_index(op.f('idx_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('idx_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_project_images_project_id'), 'project_images', ['project_id'], unique=False)
    op.create_index(op.f('idx_otps_is_used'), 'otps', ['is_used'], unique=False)
    op.create_index(op.f('idx_otps_email_used_expires'), 'otps', ['email', 'is_used', 'expires_at'], unique=False)
    op.create_index(op.f('idx_otps_email_expires'), 'otps', ['email', 'expires_at'], unique=False)
    op.create_index(op.f('idx_otps_email'), 'otps', ['email'], unique=False)
    op.create_index(op.f('idx_otps_created_at'), 'otps', ['created_at'], unique=False)
    op.create_index(op.f('idx_locations_name'), 'locations', ['name'], unique=False)
    op.create_index(op.f('idx_locations_is_deleted'), 'locations', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_locations_code'), 'locations', ['code'], unique=False)
    op.create_index(op.f('idx_education_facilities_name'), 'education_facilities', ['name'], unique=False)
    op.create_index(op.f('idx_education_facilities_is_deleted'), 'education_facilities', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_education_facilities_country'), 'education_facilities', ['country'], unique=False)
    op.create_index(op.f('idx_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('idx_companies_is_deleted'), 'companies', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_companies_country'), 'companies', ['country'], unique=False)
    op.create_index(op.f('idx_certification_centers_name'), 'certification_centers', ['name'], unique=False)
    op.create_index(op.f('idx_certification_centers_is_deleted'), 'certification_centers', ['is_deleted'], unique=False)
    op.drop_index(op.f('ix_full_time_jobs_title'), table_name='full_time_jobs')
    op.drop_index(op.f('ix_full_time_jobs_id'), table_name='full_time_jobs')
    op.drop_table('full_time_jobs')
    op.drop_index(op.f('ix_corporate_profiles_id'), table_name='corporate_profiles')
    op.drop_index(op.f('ix_corporate_profiles_company_name'), table_name='corporate_profiles')
    op.drop_table('corporate_profiles')
    # ### end Alembic commands ### 