"""add_job_skills_junction_tables

Revision ID: 44fcefde72d6
Revises: 3abc12345678
Create Date: 2025-08-27 10:11:42.738276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44fcefde72d6'
down_revision = '3abc12345678'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gig_job_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gig_job_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['gig_job_id'], ['gig_jobs.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gig_job_skills_id'), 'gig_job_skills', ['id'], unique=False)
    op.create_table('full_time_job_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_time_job_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['full_time_job_id'], ['full_time_jobs.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_full_time_job_skills_id'), 'full_time_job_skills', ['id'], unique=False)
    op.drop_index(op.f('idx_certification_centers_is_deleted'), table_name='certification_centers')
    op.drop_index(op.f('idx_certification_centers_name'), table_name='certification_centers')
    op.drop_index(op.f('idx_companies_country'), table_name='companies')
    op.drop_index(op.f('idx_companies_is_deleted'), table_name='companies')
    op.drop_index(op.f('idx_companies_name'), table_name='companies')
    op.drop_index(op.f('idx_education_facilities_country'), table_name='education_facilities')
    op.drop_index(op.f('idx_education_facilities_is_deleted'), table_name='education_facilities')
    op.drop_index(op.f('idx_education_facilities_name'), table_name='education_facilities')
    
    # Fix enum type conversions with proper casting
    op.execute("ALTER TABLE full_time_jobs ALTER COLUMN job_type TYPE jobtype USING job_type::jobtype")
    op.execute("ALTER TABLE full_time_jobs ALTER COLUMN work_mode TYPE workmode USING work_mode::workmode")
    op.execute("ALTER TABLE full_time_jobs ALTER COLUMN experience_level TYPE experiencelevel USING experience_level::experiencelevel")
    op.execute("ALTER TABLE full_time_jobs ALTER COLUMN status TYPE jobstatus USING status::jobstatus")
    
    op.drop_column('full_time_jobs', 'skills_required')
    op.drop_column('gig_jobs', 'skills_required')
    op.drop_index(op.f('idx_locations_code'), table_name='locations')
    op.drop_index(op.f('idx_locations_is_deleted'), table_name='locations')
    op.drop_index(op.f('idx_locations_name'), table_name='locations')
    op.drop_index(op.f('idx_otps_created_at'), table_name='otps')
    op.drop_index(op.f('idx_otps_email'), table_name='otps')
    op.drop_index(op.f('idx_otps_email_expires'), table_name='otps')
    op.drop_index(op.f('idx_otps_email_used_expires'), table_name='otps')
    op.drop_index(op.f('idx_otps_is_used'), table_name='otps')
    op.drop_index(op.f('idx_project_images_project_id'), table_name='project_images')
    op.drop_index(op.f('idx_projects_is_deleted'), table_name='projects')
    op.drop_index(op.f('idx_projects_user_id'), table_name='projects')
    op.drop_index(op.f('idx_skills_is_deleted'), table_name='skills')
    op.drop_index(op.f('idx_skills_name'), table_name='skills')
    
    # Fix team member enum type conversions
    op.execute("ALTER TABLE team_members ALTER COLUMN role TYPE teammemberrole USING role::teammemberrole")
    op.execute("ALTER TABLE team_members ALTER COLUMN status TYPE teammemberstatus USING status::teammemberstatus")
    
    op.drop_index(op.f('idx_user_skills_skill_id'), table_name='user_skills')
    op.drop_index(op.f('idx_user_skills_user_id'), table_name='user_skills')
    op.drop_index(op.f('idx_users_apple_id'), table_name='users')
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_email_active'), table_name='users')
    op.drop_index(op.f('idx_users_facebook_id'), table_name='users')
    op.drop_index(op.f('idx_users_google_id'), table_name='users')
    op.drop_index(op.f('idx_users_is_active'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('idx_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_index(op.f('idx_users_facebook_id'), 'users', ['facebook_id'], unique=False)
    op.create_index(op.f('idx_users_email_active'), 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('idx_users_apple_id'), 'users', ['apple_id'], unique=False)
    op.create_index(op.f('idx_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_skills_skill_id'), 'user_skills', ['skill_id'], unique=False)
    op.alter_column('team_members', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='teammemberstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('team_members', 'role',
               existing_type=sa.Enum('ADMIN', 'HR_MANAGER', 'RECRUITER', 'VIEWER', name='teammemberrole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_index(op.f('idx_skills_name'), 'skills', ['name'], unique=False)
    op.create_index(op.f('idx_skills_is_deleted'), 'skills', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('idx_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_project_images_project_id'), 'project_images', ['project_id'], unique=False)
    op.create_index(op.f('idx_otps_is_used'), 'otps', ['is_used'], unique=False)
    op.create_index(op.f('idx_otps_email_used_expires'), 'otps', ['email', 'is_used', 'expires_at'], unique=False)
    op.create_index(op.f('idx_otps_email_expires'), 'otps', ['email', 'expires_at'], unique=False)
    op.create_index(op.f('idx_otps_email'), 'otps', ['email'], unique=False)
    op.create_index(op.f('idx_otps_created_at'), 'otps', ['created_at'], unique=False)
    op.create_index(op.f('idx_locations_name'), 'locations', ['name'], unique=False)
    op.create_index(op.f('idx_locations_is_deleted'), 'locations', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_locations_code'), 'locations', ['code'], unique=False)
    op.add_column('gig_jobs', sa.Column('skills_required', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('full_time_jobs', sa.Column('skills_required', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('full_time_jobs', 'status',
               existing_type=sa.Enum('ACTIVE', 'CLOSED', 'DRAFT', name='jobstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('full_time_jobs', 'experience_level',
               existing_type=sa.Enum('ENTRY_LEVEL', 'JUNIOR', 'MID_LEVEL', 'SENIOR', 'LEAD', 'DIRECTOR', name='experiencelevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('full_time_jobs', 'work_mode',
               existing_type=sa.Enum('ON_SITE', 'REMOTE', 'HYBRID', name='workmode'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('full_time_jobs', 'job_type',
               existing_type=sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', name='jobtype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_index(op.f('idx_education_facilities_name'), 'education_facilities', ['name'], unique=False)
    op.create_index(op.f('idx_education_facilities_is_deleted'), 'education_facilities', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_education_facilities_country'), 'education_facilities', ['country'], unique=False)
    op.create_index(op.f('idx_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('idx_companies_is_deleted'), 'companies', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_companies_country'), 'companies', ['country'], unique=False)
    op.create_index(op.f('idx_certification_centers_name'), 'certification_centers', ['name'], unique=False)
    op.create_index(op.f('idx_certification_centers_is_deleted'), 'certification_centers', ['is_deleted'], unique=False)
    op.drop_index(op.f('ix_full_time_job_skills_id'), table_name='full_time_job_skills')
    op.drop_table('full_time_job_skills')
    op.drop_index(op.f('ix_gig_job_skills_id'), table_name='gig_job_skills')
    op.drop_table('gig_job_skills')
    # ### end Alembic commands ### 