"""add_user_languages_table

Revision ID: 7d8d48672b3e
Revises: 77e1a32335e2
Create Date: 2025-08-05 09:35:09.798288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d8d48672b3e'
down_revision = '77e1a32335e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_certification_centers_is_deleted'), table_name='certification_centers')
    op.drop_index(op.f('idx_certification_centers_name'), table_name='certification_centers')
    op.drop_index(op.f('idx_companies_country'), table_name='companies')
    op.drop_index(op.f('idx_companies_is_deleted'), table_name='companies')
    op.drop_index(op.f('idx_companies_name'), table_name='companies')
    op.drop_index(op.f('idx_education_facilities_country'), table_name='education_facilities')
    op.drop_index(op.f('idx_education_facilities_is_deleted'), table_name='education_facilities')
    op.drop_index(op.f('idx_education_facilities_name'), table_name='education_facilities')
    op.drop_index(op.f('idx_locations_code'), table_name='locations')
    op.drop_index(op.f('idx_locations_is_deleted'), table_name='locations')
    op.drop_index(op.f('idx_locations_name'), table_name='locations')
    op.drop_index(op.f('idx_otps_created_at'), table_name='otps')
    op.drop_index(op.f('idx_otps_email'), table_name='otps')
    op.drop_index(op.f('idx_otps_email_expires'), table_name='otps')
    op.drop_index(op.f('idx_otps_email_used_expires'), table_name='otps')
    op.drop_index(op.f('idx_otps_is_used'), table_name='otps')
    op.drop_index(op.f('idx_project_images_project_id'), table_name='project_images')
    op.drop_index(op.f('idx_projects_is_deleted'), table_name='projects')
    op.drop_index(op.f('idx_projects_user_id'), table_name='projects')
    op.drop_index(op.f('idx_skills_is_deleted'), table_name='skills')
    op.drop_index(op.f('idx_skills_name'), table_name='skills')
    op.drop_index(op.f('idx_user_skills_skill_id'), table_name='user_skills')
    op.drop_index(op.f('idx_user_skills_user_id'), table_name='user_skills')
    op.drop_index(op.f('idx_users_apple_id'), table_name='users')
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_email_active'), table_name='users')
    op.drop_index(op.f('idx_users_facebook_id'), table_name='users')
    op.drop_index(op.f('idx_users_google_id'), table_name='users')
    op.drop_index(op.f('idx_users_is_active'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('idx_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_index(op.f('idx_users_facebook_id'), 'users', ['facebook_id'], unique=False)
    op.create_index(op.f('idx_users_email_active'), 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('idx_users_apple_id'), 'users', ['apple_id'], unique=False)
    op.create_index(op.f('idx_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_skills_skill_id'), 'user_skills', ['skill_id'], unique=False)
    op.create_index(op.f('idx_skills_name'), 'skills', ['name'], unique=False)
    op.create_index(op.f('idx_skills_is_deleted'), 'skills', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('idx_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_project_images_project_id'), 'project_images', ['project_id'], unique=False)
    op.create_index(op.f('idx_otps_is_used'), 'otps', ['is_used'], unique=False)
    op.create_index(op.f('idx_otps_email_used_expires'), 'otps', ['email', 'is_used', 'expires_at'], unique=False)
    op.create_index(op.f('idx_otps_email_expires'), 'otps', ['email', 'expires_at'], unique=False)
    op.create_index(op.f('idx_otps_email'), 'otps', ['email'], unique=False)
    op.create_index(op.f('idx_otps_created_at'), 'otps', ['created_at'], unique=False)
    op.create_index(op.f('idx_locations_name'), 'locations', ['name'], unique=False)
    op.create_index(op.f('idx_locations_is_deleted'), 'locations', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_locations_code'), 'locations', ['code'], unique=False)
    op.create_index(op.f('idx_education_facilities_name'), 'education_facilities', ['name'], unique=False)
    op.create_index(op.f('idx_education_facilities_is_deleted'), 'education_facilities', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_education_facilities_country'), 'education_facilities', ['country'], unique=False)
    op.create_index(op.f('idx_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('idx_companies_is_deleted'), 'companies', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_companies_country'), 'companies', ['country'], unique=False)
    op.create_index(op.f('idx_certification_centers_name'), 'certification_centers', ['name'], unique=False)
    op.create_index(op.f('idx_certification_centers_is_deleted'), 'certification_centers', ['is_deleted'], unique=False)
    # ### end Alembic commands ### 