"""add phone_code to locations

Revision ID: c74fa4791633
Revises: fix_chat_rooms_updated_at
Create Date: 2025-10-24 10:54:49.996593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c74fa4791633'
down_revision: Union[str, Sequence[str], None] = 'fix_chat_rooms_updated_at'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('phone_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'phone_code')
    # ### end Alembic commands ###
