"""add roles and user_roles

Revision ID: d0177b6bc8cd
Revises: f30425e8dd60
Create Date: 2025-07-22 22:26:49.060658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0177b6bc8cd'
down_revision = 'f30425e8dd60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 