"""add_phone_unique_constraint

Revision ID: d17e6656afb9
Revises: 378903ef9acf
Create Date: 2025-08-25 21:01:28.910197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd17e6656afb9'
down_revision = '378903ef9acf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_languages_id'), table_name='user_languages')
    op.drop_table('user_languages')
    op.drop_index(op.f('idx_certification_centers_is_deleted'), table_name='certification_centers')
    op.drop_index(op.f('idx_certification_centers_name'), table_name='certification_centers')
    op.drop_index(op.f('idx_companies_country'), table_name='companies')
    op.drop_index(op.f('idx_companies_is_deleted'), table_name='companies')
    op.drop_index(op.f('idx_companies_name'), table_name='companies')
    op.drop_index(op.f('idx_education_facilities_country'), table_name='education_facilities')
    op.drop_index(op.f('idx_education_facilities_is_deleted'), table_name='education_facilities')
    op.drop_index(op.f('idx_education_facilities_name'), table_name='education_facilities')
    op.drop_index(op.f('idx_locations_code'), table_name='locations')
    op.drop_index(op.f('idx_locations_is_deleted'), table_name='locations')
    op.drop_index(op.f('idx_locations_name'), table_name='locations')
    op.drop_index(op.f('idx_otps_created_at'), table_name='otps')
    op.drop_index(op.f('idx_otps_email'), table_name='otps')
    op.drop_index(op.f('idx_otps_email_expires'), table_name='otps')
    op.drop_index(op.f('idx_otps_email_used_expires'), table_name='otps')
    op.drop_index(op.f('idx_otps_is_used'), table_name='otps')
    op.drop_index(op.f('idx_project_images_project_id'), table_name='project_images')
    op.drop_constraint(op.f('project_images_project_id_fkey'), 'project_images', type_='foreignkey')
    op.create_foreign_key(None, 'project_images', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_projects_is_deleted'), table_name='projects')
    op.drop_index(op.f('idx_projects_user_id'), table_name='projects')
    op.drop_constraint(op.f('projects_user_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_skills_is_deleted'), table_name='skills')
    op.drop_index(op.f('idx_skills_name'), table_name='skills')
    op.drop_index(op.f('idx_user_skills_skill_id'), table_name='user_skills')
    op.drop_index(op.f('idx_user_skills_user_id'), table_name='user_skills')
    op.drop_index(op.f('idx_users_apple_id'), table_name='users')
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_email_active'), table_name='users')
    op.drop_index(op.f('idx_users_facebook_id'), table_name='users')
    op.drop_index(op.f('idx_users_google_id'), table_name='users')
    op.drop_index(op.f('idx_users_is_active'), table_name='users')
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('idx_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('idx_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_index(op.f('idx_users_facebook_id'), 'users', ['facebook_id'], unique=False)
    op.create_index(op.f('idx_users_email_active'), 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('idx_users_apple_id'), 'users', ['apple_id'], unique=False)
    op.create_index(op.f('idx_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_skills_skill_id'), 'user_skills', ['skill_id'], unique=False)
    op.create_index(op.f('idx_skills_name'), 'skills', ['name'], unique=False)
    op.create_index(op.f('idx_skills_is_deleted'), 'skills', ['is_deleted'], unique=False)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_user_id_fkey'), 'projects', 'users', ['user_id'], ['id'])
    op.create_index(op.f('idx_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('idx_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.drop_constraint(None, 'project_images', type_='foreignkey')
    op.create_foreign_key(op.f('project_images_project_id_fkey'), 'project_images', 'projects', ['project_id'], ['id'])
    op.create_index(op.f('idx_project_images_project_id'), 'project_images', ['project_id'], unique=False)
    op.create_index(op.f('idx_otps_is_used'), 'otps', ['is_used'], unique=False)
    op.create_index(op.f('idx_otps_email_used_expires'), 'otps', ['email', 'is_used', 'expires_at'], unique=False)
    op.create_index(op.f('idx_otps_email_expires'), 'otps', ['email', 'expires_at'], unique=False)
    op.create_index(op.f('idx_otps_email'), 'otps', ['email'], unique=False)
    op.create_index(op.f('idx_otps_created_at'), 'otps', ['created_at'], unique=False)
    op.create_index(op.f('idx_locations_name'), 'locations', ['name'], unique=False)
    op.create_index(op.f('idx_locations_is_deleted'), 'locations', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_locations_code'), 'locations', ['code'], unique=False)
    op.create_index(op.f('idx_education_facilities_name'), 'education_facilities', ['name'], unique=False)
    op.create_index(op.f('idx_education_facilities_is_deleted'), 'education_facilities', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_education_facilities_country'), 'education_facilities', ['country'], unique=False)
    op.create_index(op.f('idx_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('idx_companies_is_deleted'), 'companies', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_companies_country'), 'companies', ['country'], unique=False)
    op.create_index(op.f('idx_certification_centers_name'), 'certification_centers', ['name'], unique=False)
    op.create_index(op.f('idx_certification_centers_is_deleted'), 'certification_centers', ['is_deleted'], unique=False)
    op.create_table('user_languages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('user_languages_language_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_languages_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_languages_pkey'))
    )
    op.create_index(op.f('ix_user_languages_id'), 'user_languages', ['id'], unique=False)
    # ### end Alembic commands ### 