"""Add NewModel table

Revision ID: d4cd2c1f665d
Revises: 112a2c60c42f
Create Date: 2025-07-25 14:04:04.901315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4cd2c1f665d'
down_revision = '112a2c60c42f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_certification_centers_id'), 'certification_centers', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('education_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_education_facilities_id'), 'education_facilities', ['id'], unique=False)
    op.add_column('certifications', sa.Column('certification_center_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'certifications', 'certification_centers', ['certification_center_id'], ['id'])
    op.drop_column('certifications', 'publishing_organization')
    op.add_column('educations', sa.Column('education_facility_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'educations', 'education_facilities', ['education_facility_id'], ['id'])
    op.drop_column('educations', 'school')
    op.add_column('experiences', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'experiences', 'companies', ['company_id'], ['id'])
    op.drop_column('experiences', 'company')
    op.add_column('users', sa.Column('language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'languages', ['language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'language_id')
    op.add_column('experiences', sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'experiences', type_='foreignkey')
    op.drop_column('experiences', 'company_id')
    op.add_column('educations', sa.Column('school', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.drop_column('educations', 'education_facility_id')
    op.add_column('certifications', sa.Column('publishing_organization', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'certifications', type_='foreignkey')
    op.drop_column('certifications', 'certification_center_id')
    op.drop_index(op.f('ix_education_facilities_id'), table_name='education_facilities')
    op.drop_table('education_facilities')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_certification_centers_id'), table_name='certification_centers')
    op.drop_table('certification_centers')
    # ### end Alembic commands ### 